query advisedProjects(
    $advisers: [ID!]
) {
  projects (advisers: $advisers) {
    edges {
      node {
        id
        title
        description
        teamName
        status
        objectives{
          edges{
            node{
              id
              name
              status
            }
          }
        }
        categories{
          edges{
            node{
              id
              name
            }
          }
        }
        feedbacks{
          edges{
            node{
              id
              message
              createdAt
            }
          }
        }
        updatedAt
      }
    }
  }
}