export const ADVISER_ACTIONS = {
  UPDATE_INVITATION: "UPDATE_INVITATION",
  FETCH_INVITATIONS: "FETCH_INVITATIONS",
  FETCH_MEMBERSHIPS: "GET_MEMBERSHIPS",
  FETCH_TEAM: "FETCH_TEAM",
  FETCH_PENDING_PROPOSALS: "FETCH_PENDING_PROPOSALS",
  FETCH_ONE_PENDING_PROPOSAL: "FETCH_ONE_PENDING_PROPOSAL",
};
