export const ADVISER_GETTERS = {
  GET_INVITATIONS: "GET_INVITATIONS",
  GET_MEMBERSHIPS: "GET_MEMBERSHIPS",
  GET_HAS_MEMBERSHIPS: "GET_HAS_MEMBERSHIPS",
  GET_TEAM: "GET_TEAM",
  GET_PROPOSALS: "GET_PROPOSALS",
};
