export const ADVISER_MUTATIONS = {
  SET_INVITATIONS: "SET_INVITATIONS",
  SET_UPDATE_INVITATION: "SET_UPDATE_INVITATION",
  SET_MEMBERSHIPS: "SET_MEMBERSHIPS",
  SET_HAS_MEMBERSHIPS: "SET_HAS_MEMBERSHIPS",
  SET_RESET_ADVISER_STATE: "SET_RESET_ADVISER_STATE",
};
