export const ADVISER_MUTATIONS = {
  SET_INVITATIONS: "SET_INVITATIONS",
  SET_UPDATE_INVITATION: "SET_UPDATE_INVITATION",
  SET_MEMBERSHIPS: "SET_MEMBERSHIPS",
  SET_HAS_MEMBERSHIPS: "SET_HAS_MEMBERSHIPS",
  SET_RESET_ADVISER_STATE: "SET_RESET_ADVISER_STATE",
  ADD_TEAM: "ADD_TEAM",
  ADD_PENDING_PROPOSAL: "ADD_PENDING_PROPOSAL",
  UPDATE_ONE_PENDING_PROPOSAL: "UPDATE_ONE_PENDING_PROPOSAL",
};
