export const ROOT_ACTIONS = {
  LOGIN_USER: "LOGIN_USER",
  SIGNUP_USER: "SIGNUP_USER",
  GET_USER_INFO: "GET_USER_INFO",
  ONBOARD_USER: "ONBOARD_USER",
  FETCH_SCHOOLS: "FETCH_SCHOOLS",
  LOGOUT_USER: "LOGOUT_USER",
};
