export const ROOT_ACTIONS = {
  LOGIN_USER: "LOGIN_USER",
  SIGNUP_USER: "SIGNUP_USER",
  GET_USER_INFO: "GET_USER_INFO",
  ONBOARD_USER: "ONBOARD_USER",
  UPDATE_USER: "UPDATE_USER",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  FETCH_SCHOOLS: "FETCH_SCHOOLS",
  SEND_PASSWORD_RESET_LINK: "SEND_PASSWORD_RESET_LINK",
  RESET_PASSWORD: "RESET_PASSWORD",
  VERIFY_ACCOUNT: "VERIFY_ACCOUNT",
  RESEND_VERIFICATION_LINK: "RESEND_VERIFICATION_LINK",
  LOGOUT_USER: "LOGOUT_USER",
};
