export const ROOT_GETTERS = {
  GET_USER: "GET_USER",
  GET_TOKEN_ACCESS: "GET_TOKEN_ACCESS",
  GET_TOKEN_REFRESH: "GET_TOKEN_REFRESH",
  GET_IS_LOGGED_IN: "GET_IS_LOGGED_IN",
  GET_USER_TYPE: "GET_USER_TYPE",
  GET_SCHOOLS: "GET_SCHOOLS",
  GET_CURRENT_SCHOOL: "GET_CURRENT_SCHOOL",
  GET_USER_META: "GET_USER_META",
  GET_ARCHIVES: "GET_ARCHIVES",
  GET_CURRENT_ARCHIVE_RESEARCH: "GET_CURRENT_ARCHIVE_RESEARCH",
};
