export const ROOT_MUTATIONS = {
  SET_USER: "SET_USER",
  SET_TOKEN_ACCESS: "SET_TOKEN_ACCESS",
  SET_TOKEN_REFRESH: "SET_TOKEN_REFRESH",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
  SET_USER_TYPE: "SET_USER_TYPE",
  SET_SCHOOLS: "SET_SCHOOLS",
  SET_RESET_ROOT_STATE: "SET_RESET_ROOT_STATE",
  SET_CURRENT_SCHOOL: "SET_CURRENT_SCHOOL",
  SET_USER_META: "SET_USER_META",
  SET_ARCHIVES: "SET_ARCHIVES",
  SET_ONE_ARCHIVE_RESEARCH: "SET_ONE_ARCHIVE_RESEARCH",
};
