export const STUDENT_GETTERS = {
  GET_CURRENT_CREATED_TEAM: "GET_CURRENT_CREATED_TEAM",
  GET_SENT_MEMBERS_INVITATIONS: "GET_SENT_MEMBERS_INVITATIONS",
  GET_SENT_TEACHERS_INVITATIONS: "GET_SENT_TEACHERS_INVITATIONS",
  GET_INVITATIONS: "GET_INVITATIONS",
  GET_MEMBERSHIPS: "GET_MEMBERSHIPS",
  GET_HAS_MEMBERSHIPS: "GET_HAS_MEMBERSHIPS",
  GET_SELECTED_TEAM_DETAILS: "GET_TEAM_DETAILS",
};
