export const STUDENT_MUTATIONS = {
  SET_CURRENT_CREATED_TEAM: "SET_CURRENT_CREATED_TEAM",
  SET_SENT_MEMBERS_INVITATIONS: "SET_SENT_MEMBERS_INVITATIONS",
  SET_SENT_TEACHERS_INVITATIONS: "SET_SENT_TEACHERS_INVITATIONS",
  SET_INVITATIONS: "SET_INVITATIONS",
  SET_UPDATE_INVITATION: "SET_UPDATE_INVITATION",
  SET_MEMBERSHIPS: "SET_MEMBERSHIPS",
  SET_HAS_MEMBERSHIPS: "SET_HAS_MEMBERSHIPS",
<<<<<<< HEAD:src/modules/student/store/types/_mutations.js
  SET_SELECTED_TEAM: "SET_SELECTED_TEAM",
  SET_RESET_STUDENT_STATE: "SET_RESET_STUDENT_STATE",
=======
  SET_RESET_STUDENT_STATE: "SET_RESET_STUDENT_STATE",
  SET_SELECTED_TEAM_DETAILS: "SET_SELECTED_TEAM_DETAILS",
>>>>>>> feature/tiptap:src/modules/student/store/types/mutations.js
};
