export const STUDENT_ACTIONS = {
  CREATE_TEAM: "CREATE_TEAM",
  SEND_MEMBERS_INVITATIONS: "SEND_MEMBERS_INVITATIONS",
  SEND_TEACHERS_INVITATIONS: "SEND_TEACHERS_INVITATIONS",
  UPDATE_INVITATION: "UPDATE_INVITATION",
  FETCH_INVITATIONS: "FETCH_INVITATIONS",
  FETCH_MEMBERSHIPS: "GET_MEMBERSHIPS",
};
