export const MUTATIONS = {
  SET_TEAM: "SET_TEAM",
  SET_SENT_MEMBERS_INVITATIONS: "SET_SENT_MEMBERS_INVITATIONS",
  SET_SENT_TEACHERS_INVITATIONS: "SET_SENT_TEACHERS_INVITATIONS",
  SET_INVITATIONS: "SET_INVITATIONS",
};
