export const STUDENT_MUTATIONS = {
  SET_CURRENT_CREATED_TEAM: "SET_CURRENT_CREATED_TEAM",
  SET_SENT_MEMBERS_INVITATIONS: "SET_SENT_MEMBERS_INVITATIONS",
  SET_SENT_TEACHERS_INVITATIONS: "SET_SENT_TEACHERS_INVITATIONS",
  SET_INVITATIONS: "SET_INVITATIONS",
  SET_UPDATE_INVITATION: "SET_UPDATE_INVITATION",
  SET_MEMBERSHIPS: "SET_MEMBERSHIPS",
  SET_HAS_MEMBERSHIPS: "SET_HAS_MEMBERSHIPS",
};
