query invitations ($invitedEmail: String!) {
  invitations (invitedEmail: $invitedEmail ) {
    edges {
      node {
        id
        pk
        user{
          id
          firstName
          lastName
        }
        project {
          id
          pk
          teamName
          description
        }
        status
        createdAt
      }
    }
  }
}